#ifndef BATTLE_STATUS_H
#define BATTLE_STATUS_H

typedef enum BattleStatusId {
    BATTLE_STATUS_NONE = 0,
    BATTLE_STATUS_BURN,
    BATTLE_STATUS_POISON,
    BATTLE_STATUS_CURSE,
    BATTLE_STATUS_PARALYSIS,
    BATTLE_STATUS_FROZEN,
    BATTLE_STATUS_CONFUSED,
    BATTLE_STATUS_SEEDED,
    BATTLE_STATUS_CONFUSED2,
    BATTLE_STATUS_DOWNED,
    BATTLE_STATUS_DARK,
    BATTLE_STATUS_LIGHT,
    BATTLE_STATUS_CHAOS,

    /* Debug-only visual placeholder; keep for existing Test Dummy hook. */
    BATTLE_STATUS_TEST_PLACEHOLDER,

    BATTLE_STATUS_COUNT
} BattleStatusId;

#define BATTLE_MEMBER_STATUS_SLOT_COUNT 3

#endif
