#ifndef BATTLE_ELEMENT_H
#define BATTLE_ELEMENT_H

typedef enum BattleElementId {
    BATTLE_ELEMENT_NONE = 0,
    BATTLE_ELEMENT_CURSE,
    BATTLE_ELEMENT_MIGHT,
    BATTLE_ELEMENT_CHAOS,
    BATTLE_ELEMENT_FIRE,
    BATTLE_ELEMENT_WATER,
    BATTLE_ELEMENT_NATURE,
    BATTLE_ELEMENT_ICE,
    BATTLE_ELEMENT_DARK,
    BATTLE_ELEMENT_LIGHT,
    BATTLE_ELEMENT_WIND,
    BATTLE_ELEMENT_POISON,
    BATTLE_ELEMENT_MENTAL,
    BATTLE_ELEMENT_COUNT
} BattleElementId;

typedef enum ElementEffectiveness {
    ELEMENT_EFFECT_NEUTRAL = 0,
    ELEMENT_EFFECT_HIGHLY_EFFECTIVE,
    ELEMENT_EFFECT_CANNOT_INFLICT
} ElementEffectiveness;

typedef enum BattleEffectivenessReaction {
    BATTLE_EFFECT_REACTION_NONE = 0,
    BATTLE_EFFECT_REACTION_NEUTRAL,
    BATTLE_EFFECT_REACTION_HIGHLY_EFFECTIVE,
    BATTLE_EFFECT_REACTION_CANNOT_INFLICT
} BattleEffectivenessReaction;

#endif
