#ifndef HUD_LAYOUT_H
#define HUD_LAYOUT_H

#include "core/gba_types.h"

#define HUD_PANEL_TITLE_Y 116
#define HUD_PANEL_BODY_Y 128
#define HUD_PANEL_BODY2_Y 140
#define HUD_PANEL_FOOTER_Y 152

#define HUD_CMD_COL_LEFT_X 24
#define HUD_CMD_COL_RIGHT_X 128
#define HUD_CMD_BASE_Y HUD_PANEL_BODY_Y
#define HUD_CMD_ROW_GAP 12
#define HUD_CMD_ROW1_Y HUD_CMD_BASE_Y
#define HUD_CMD_ROW2_Y (HUD_CMD_BASE_Y + HUD_CMD_ROW_GAP)
#define HUD_CMD_ROW3_Y (HUD_CMD_BASE_Y + (HUD_CMD_ROW_GAP * 2))

#define HUD_COMMAND_PANEL_TOP_Y 112
#define HUD_COMMAND_PANEL_HEIGHT 48
#define HUD_COMMAND_PANEL_FILL RGB15(8, 8, 16)
#define HUD_COMMAND_PANEL_BORDER_THICKNESS 2

/*
 * Skills detail card (M2/M3). Expanded clear is Skills-phase only; leaving Skills
 * must restore field pixels for y=[108,112) via FIELD dirty (see battle.c).
 */
#define HUD_SKILLS_PANEL_TOP_Y 108
#define HUD_SKILLS_PANEL_HEIGHT (SCREEN_HEIGHT - HUD_SKILLS_PANEL_TOP_Y)
/* Outer Skills panel fill = card text navy #102039 (not command purple). */
#define HUD_SKILLS_PANEL_FILL RGB15(2, 4, 7)

#define HUD_SKILLS_TITLE_Y 110
#define HUD_SKILLS_COUNT_X 196
#define HUD_SKILLS_CARD_X 8
#define HUD_SKILLS_CARD_Y 119
#define HUD_SKILLS_CARD_W 224
#define HUD_SKILLS_CARD_H 34
#define HUD_SKILLS_CARD_INSET_X 10
#define HUD_SKILLS_CARD_NAME_Y 121
#define HUD_SKILLS_CARD_META_Y 129
#define HUD_SKILLS_CARD_SC_Y 137
#define HUD_SKILLS_CARD_EFFECT_Y 145
#define HUD_SKILLS_META_CAT_X 58
#define HUD_SKILLS_META_PWR_X 100
#define HUD_SKILLS_TARGET_X 100
#define HUD_SKILLS_FOOTER_Y 153

/* Skill-slot indicator circles (screen-space, above card). */
#define HUD_SKILLS_INDICATOR_SIZE 7
#define HUD_SKILLS_INDICATOR_Y \
    (HUD_SKILLS_PANEL_TOP_Y + ((HUD_SKILLS_CARD_Y - HUD_SKILLS_PANEL_TOP_Y - HUD_SKILLS_INDICATOR_SIZE) / 2))
#define HUD_SKILLS_INDICATOR_CX0 108
#define HUD_SKILLS_INDICATOR_CX1 120
#define HUD_SKILLS_INDICATOR_CX2 132
#define HUD_SKILLS_INDICATOR_SELECTED RGB15(31, 19, 0) /* #FF9C00 */

/* Host viewport: entire temporary card travels through this region. */
#define HUD_SKILLS_CARD_VIEW_X 0
#define HUD_SKILLS_CARD_VIEW_Y HUD_SKILLS_CARD_Y
#define HUD_SKILLS_CARD_VIEW_W SCREEN_WIDTH
#define HUD_SKILLS_CARD_VIEW_H HUD_SKILLS_CARD_H
#define HUD_SKILLS_CARD_BORDER RGB15(18, 18, 28)
#define HUD_SKILLS_SC_WARN RGB15(31, 18, 8)
#define HUD_SKILLS_SLIDE_FRAME_COUNT 3

#define HUD_MESSAGE_BOX_INSET_X 8
#define HUD_MESSAGE_BOX_INSET_Y (HUD_COMMAND_PANEL_TOP_Y + 6)
#define HUD_MESSAGE_BOX_W 224
#define HUD_MESSAGE_BOX_H 36
#define HUD_MESSAGE_TEXT_X 12
#define HUD_MESSAGE_TEXT_Y (HUD_MESSAGE_BOX_INSET_Y + 10)
#define HUD_MESSAGE_BOX_FILL RGB15(4, 6, 24)
#define HUD_MESSAGE_BOX_BORDER_THICKNESS 2

#define HUD_BORDER_BLUE RGB15(8, 16, 31)
#define HUD_BORDER_RED RGB15(31, 8, 8)
#define HUD_BORDER_GREEN RGB15(8, 28, 10)
#define HUD_BORDER_GRAY RGB15(18, 18, 20)
#define HUD_BORDER_PURPLE RGB15(22, 8, 28)
#define HUD_BORDER_GOLD RGB15(31, 26, 6)
#define HUD_BORDER_CYAN RGB15(6, 28, 31)
#define HUD_BORDER_PINK RGB15(31, 14, 22)

typedef enum BorderColor {
    BORDER_COLOR_BLUE = 0,
    BORDER_COLOR_RED,
    BORDER_COLOR_GREEN,
    BORDER_COLOR_GRAY,
    BORDER_COLOR_PURPLE,
    BORDER_COLOR_GOLD,
    BORDER_COLOR_CYAN,
    BORDER_COLOR_PINK,
    BORDER_COLOR_COUNT
} BorderColor;

#define BATTLE_FIELD_TILE_BOTTOM_GAP 2
#define BATTLE_SLOT_TILE_H 22
#define BATTLE_ALLY_BACK_ROW_TILE_Y 85
/* Ally slot 4 may extend partially behind the command panel for team separation. */
#define BATTLE_FIELD_TILE_OFFSET_Y 16
#define BATTLE_HP_BAR_OFFSET_Y 2

#define HUD_SKILL_COL_LEFT_X 16
#define HUD_SKILL_COL_RIGHT_X 128
#define HUD_SKILL_ROW1_Y 126
#define HUD_SKILL_ROW_GAP 16
#define HUD_SKILL_ROW2_Y (HUD_SKILL_ROW1_Y + HUD_SKILL_ROW_GAP)
#define HUD_SKILL_BOX_W 104
#define HUD_SKILL_BOX_H 16
#define HUD_SKILL_NAME_X_PAD 4
#define HUD_SKILL_SC_LINE_OFFSET 8

#define HUD_SKILL_ROW_START_Y HUD_PANEL_BODY_Y
#define HUD_SKILL_ROW_SPACING 12
#define HUD_SKILL_SC_X 176
#define HUD_SKILL_UNDERLINE_W (HUD_SKILL_SC_X - 16)

#define HUD_ITEM_COL_LEFT_X 16
#define HUD_ITEM_ROW1_Y 126
#define HUD_ITEM_ROW_GAP 16
#define HUD_ITEM_ROW2_Y (HUD_ITEM_ROW1_Y + HUD_ITEM_ROW_GAP)
#define HUD_ITEM_BOX_W 208
#define HUD_ITEM_BOX_H 12
#define HUD_ITEM_NAME_X_PAD 4
#define HUD_ITEM_COUNT_X 196

#define HUD_PLAYER_BOX_X 8
#define HUD_PLAYER_BOX_Y 32
#define HUD_PLAYER_BOX_W 72
#define HUD_PLAYER_BOX_H 52
#define HUD_PLAYER_SPRITE_X 16
#define HUD_PLAYER_SPRITE_Y 40
#define HUD_PLAYER_STAT_X 12
#define HUD_PLAYER_STAT_Y 36
#define HUD_PLAYER_CURSOR_Y 44

#define HUD_TEXT_TITLE RGB15(24, 24, 31)
#define HUD_TEXT_LIGHT RGB15(31, 31, 31)
#define HUD_TEXT_MUTED RGB15(20, 20, 20)
#define HUD_TEXT_HIGHLIGHT RGB15(31, 28, 0)

#endif
