/* AUTOGENERATED, DO NOT EDIT
 * Source: assets_src/overworld/maps/overworld_test.tmx
 * Tool: tools/compile_tiled_map.py
 */
#ifndef GOVERWORLDTESTMAP_H
#define GOVERWORLDTESTMAP_H

#include "core/gba_types.h"

#define gOverworldTestMap_WIDTH_METATILES 40
#define gOverworldTestMap_HEIGHT_METATILES 30
#define gOverworldTestMap_CELL_COUNT (gOverworldTestMap_WIDTH_METATILES * gOverworldTestMap_HEIGHT_METATILES)
#define gOverworldTestMap_TILESET_METATILE_COUNT 3
#define gOverworldTestMap_FALLBACK_METATILE_ID 0
#define gOverworldTestMap_COLLISION_PROFILE_COUNT 6

extern const u16 gOverworldTestMapMetatileIds[gOverworldTestMap_CELL_COUNT];
extern const u8 gOverworldTestMapCollisionProfileIds[gOverworldTestMap_CELL_COUNT];
extern const u16 gOverworldTestMapCollisionProfileMasks[gOverworldTestMap_COLLISION_PROFILE_COUNT];

#endif
