#ifndef AKSIL_FRONT_SPRITE_H
#define AKSIL_FRONT_SPRITE_H

#include "core/gba_types.h"

#define AKSIL_FRONT_SPRITE_WIDTH 64
#define AKSIL_FRONT_SPRITE_HEIGHT 64
#define AKSIL_FRONT_SPRITE_PIXEL_COUNT (AKSIL_FRONT_SPRITE_WIDTH * AKSIL_FRONT_SPRITE_HEIGHT)
#define AKSIL_FRONT_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define AKSIL_FRONT_SPRITE_KEY_COLOR AKSIL_FRONT_SPRITE_TRANSPARENT_COLOR

extern const u16 aksil_front_spriteBitmap[AKSIL_FRONT_SPRITE_PIXEL_COUNT];

#endif
