/* AUTOGENERATED, DO NOT EDIT
 * Tool: tools/convert_dialogue_portraits.py
 */
#ifndef DIALOGUE_PORTRAITS_ASSET_H
#define DIALOGUE_PORTRAITS_ASSET_H

#include "core/gba_types.h"

#define DIALOGUE_PORTRAIT_SOURCE_W 64
#define DIALOGUE_PORTRAIT_SOURCE_H 64
#define DIALOGUE_PORTRAIT_PRESENTATION_SCALE 2
#define DIALOGUE_PORTRAIT_TILE_COUNT 64
#define DIALOGUE_PORTRAIT_TILE_BYTES (DIALOGUE_PORTRAIT_TILE_COUNT * 32)
#define DIALOGUE_PORTRAIT_TILE_WORDS (DIALOGUE_PORTRAIT_TILE_BYTES / 4)
#define DIALOGUE_PORTRAIT_PALETTE_COUNT 16

/* OBJ VRAM tile bases (1D). Overworld player uses tiles 0..7. */
#define DIALOGUE_OBJ_TILE_BASE_LEFT 64
#define DIALOGUE_OBJ_TILE_BASE_RIGHT 128

extern const u16 gDialoguePortraitAksilActivePalette[DIALOGUE_PORTRAIT_PALETTE_COUNT];
extern const u16 gDialoguePortraitAksilInactivePalette[DIALOGUE_PORTRAIT_PALETTE_COUNT];
extern const u16 gDialoguePortraitProtagonistActivePalette[DIALOGUE_PORTRAIT_PALETTE_COUNT];
extern const u16 gDialoguePortraitProtagonistInactivePalette[DIALOGUE_PORTRAIT_PALETTE_COUNT];
extern const u32 gDialoguePortraitAksilTiles[DIALOGUE_PORTRAIT_TILE_WORDS];
extern const u32 gDialoguePortraitProtagonistTiles[DIALOGUE_PORTRAIT_TILE_WORDS];

_Static_assert(DIALOGUE_PORTRAIT_TILE_BYTES == 2048, "64x64 4bpp portrait is 2048 bytes");
_Static_assert(
    (DIALOGUE_OBJ_TILE_BASE_RIGHT + DIALOGUE_PORTRAIT_TILE_COUNT) <= 1024,
    "Dialogue portraits must fit in OBJ VRAM");

#endif
