/* AUTOGENERATED, DO NOT EDIT
 * Source: assets_src/ui/Dialogue Ui.png
 * Tool: tools/convert_dialogue_frame.py
 */
#ifndef DIALOGUE_FRAME_ASSET_H
#define DIALOGUE_FRAME_ASSET_H

#include "core/gba_types.h"

#define DIALOGUE_FRAME_TILE_COUNT 70
#define DIALOGUE_FRAME_TILE_WORDS (DIALOGUE_FRAME_TILE_COUNT * 8)
#define DIALOGUE_FRAME_MAP_W 32
#define DIALOGUE_FRAME_MAP_H 32
#define DIALOGUE_FRAME_MAP_ENTRIES (DIALOGUE_FRAME_MAP_W * DIALOGUE_FRAME_MAP_H)
#define DIALOGUE_FRAME_VISIBLE_TILE_W 30
#define DIALOGUE_FRAME_VISIBLE_TILE_H 20
#define DIALOGUE_FRAME_PALETTE_COUNT 16
#define DIALOGUE_FRAME_PALETTE_BANK 1

extern const u16 gDialogueFramePalette[DIALOGUE_FRAME_PALETTE_COUNT];
extern const u32 gDialogueFrameTiles[DIALOGUE_FRAME_TILE_WORDS];
extern const u16 gDialogueFrameMap[DIALOGUE_FRAME_MAP_ENTRIES];

#endif
