#ifndef ELECTRIC_ARMOR_BADGER_SPRITE_H
#define ELECTRIC_ARMOR_BADGER_SPRITE_H

#include "core/gba_types.h"

#define ELECTRIC_ARMOR_BADGER_SPRITE_WIDTH 64
#define ELECTRIC_ARMOR_BADGER_SPRITE_HEIGHT 64
#define ELECTRIC_ARMOR_BADGER_SPRITE_PIXEL_COUNT \
    (ELECTRIC_ARMOR_BADGER_SPRITE_WIDTH * ELECTRIC_ARMOR_BADGER_SPRITE_HEIGHT)
#define ELECTRIC_ARMOR_BADGER_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define ELECTRIC_ARMOR_BADGER_SPRITE_KEY_COLOR ELECTRIC_ARMOR_BADGER_SPRITE_TRANSPARENT_COLOR

#define ELECTRIC_ARMOR_BADGER_VISUAL_TOP_Y 18
#define ELECTRIC_ARMOR_BADGER_VISUAL_BOTTOM_Y 63
#define ELECTRIC_ARMOR_BADGER_VISUAL_HEIGHT 46

extern const u16 electric_armor_badger_spriteBitmap[ELECTRIC_ARMOR_BADGER_SPRITE_PIXEL_COUNT];

#endif
