#ifndef MAREN_FRONT_SPRITE_H
#define MAREN_FRONT_SPRITE_H

#include "core/gba_types.h"

#define MAREN_FRONT_SPRITE_WIDTH 64
#define MAREN_FRONT_SPRITE_HEIGHT 64
#define MAREN_FRONT_SPRITE_PIXEL_COUNT \
    (MAREN_FRONT_SPRITE_WIDTH * MAREN_FRONT_SPRITE_HEIGHT)
#define MAREN_FRONT_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define MAREN_FRONT_SPRITE_KEY_COLOR MAREN_FRONT_SPRITE_TRANSPARENT_COLOR

extern const u16 maren_front_spriteBitmap[MAREN_FRONT_SPRITE_PIXEL_COUNT];

#endif
