#ifndef PETALBURG_BATTLE_BACKGROUND_H
#define PETALBURG_BATTLE_BACKGROUND_H

#include "core/gba_types.h"

#define PETALBURG_BATTLE_BACKGROUND_WIDTH 240
#define PETALBURG_BATTLE_BACKGROUND_HEIGHT 112
#define PETALBURG_BATTLE_BACKGROUND_PIXEL_COUNT \
    (PETALBURG_BATTLE_BACKGROUND_WIDTH * PETALBURG_BATTLE_BACKGROUND_HEIGHT)

extern const u16 gPetalburgBattleBackgroundPixels[PETALBURG_BATTLE_BACKGROUND_PIXEL_COUNT];

#endif
