#ifndef PLACE_HOLDER_ENEMY_SPRITE_H
#define PLACE_HOLDER_ENEMY_SPRITE_H

#include "core/gba_types.h"

#define PLACE_HOLDER_ENEMY_SPRITE_WIDTH 64
#define PLACE_HOLDER_ENEMY_SPRITE_HEIGHT 64
#define PLACE_HOLDER_ENEMY_SPRITE_PIXEL_COUNT \
    (PLACE_HOLDER_ENEMY_SPRITE_WIDTH * PLACE_HOLDER_ENEMY_SPRITE_HEIGHT)
#define PLACE_HOLDER_ENEMY_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define PLACE_HOLDER_ENEMY_SPRITE_KEY_COLOR PLACE_HOLDER_ENEMY_SPRITE_TRANSPARENT_COLOR

#define PLACE_HOLDER_ENEMY_VISUAL_TOP_Y 18
#define PLACE_HOLDER_ENEMY_VISUAL_BOTTOM_Y 63
#define PLACE_HOLDER_ENEMY_VISUAL_HEIGHT 46

extern const u16 place_holder_enemy_spriteBitmap[PLACE_HOLDER_ENEMY_SPRITE_PIXEL_COUNT];

#endif
