#ifndef PROTAGONIST_FRONT_SPRITE_H
#define PROTAGONIST_FRONT_SPRITE_H

#include "core/gba_types.h"

#define PROTAGONIST_FRONT_SPRITE_WIDTH 66
#define PROTAGONIST_FRONT_SPRITE_HEIGHT 66
#define PROTAGONIST_FRONT_SPRITE_PIXEL_COUNT \
    (PROTAGONIST_FRONT_SPRITE_WIDTH * PROTAGONIST_FRONT_SPRITE_HEIGHT)
#define PROTAGONIST_FRONT_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define PROTAGONIST_FRONT_SPRITE_KEY_COLOR PROTAGONIST_FRONT_SPRITE_TRANSPARENT_COLOR

extern const u16 protagonist_front_spriteBitmap[PROTAGONIST_FRONT_SPRITE_PIXEL_COUNT];

#endif
