#ifndef TUTSIL_FRONT_SPRITE_H
#define TUTSIL_FRONT_SPRITE_H

#include "core/gba_types.h"

#define TUTSIL_FRONT_SPRITE_WIDTH 66
#define TUTSIL_FRONT_SPRITE_HEIGHT 66
#define TUTSIL_FRONT_SPRITE_PIXEL_COUNT \
    (TUTSIL_FRONT_SPRITE_WIDTH * TUTSIL_FRONT_SPRITE_HEIGHT)
#define TUTSIL_FRONT_SPRITE_TRANSPARENT_COLOR RGB15(31, 0, 31)
#define TUTSIL_FRONT_SPRITE_KEY_COLOR TUTSIL_FRONT_SPRITE_TRANSPARENT_COLOR

extern const u16 tutsil_front_spriteBitmap[TUTSIL_FRONT_SPRITE_PIXEL_COUNT];

#endif
