#!/usr/bin/env python3
"""Convert Dialogue Ui.png to Mode 0 4bpp BG tiles + map (Milestone 2)."""

from __future__ import annotations

import argparse
import hashlib
import os
import tempfile
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]

# Approved frame colors (RGBA) → 4bpp indices inside palette bank 1.
SOURCE_TO_INDEX: dict[tuple[int, int, int, int], int] = {
    (0, 0, 0, 0): 0,
    (0, 0, 0, 255): 1,
    (252, 156, 0, 255): 2,  # orange
    (255, 211, 140, 255): 3,  # light gold
    (253, 191, 90, 255): 4,  # gold
}

# RGB15 matching the approved GBA mapping (same as mockup / resource docs).
PALETTE_RGB15 = [
    0x0000,  # 0 transparent
    0x0000,  # 1 black
    0x025E,  # 2 orange RGB15(30,18,0) from (252,156,0)
    0x473F,  # 3 light gold RGB15(31,25,17) from (255,211,140)
    0x2AFE,  # 4 gold RGB15(30,23,10) from (253,191,90)
]

SOURCE_HASH = "bf25ec599900e1443c725879ea4e200a65426249448d00f18f47e48be5a0072b"

MAP_W = 32
MAP_H = 32
VISIBLE_TILE_W = 30
VISIBLE_TILE_H = 20


def rgb15_from_rgb888(r: int, g: int, b: int) -> int:
    return ((r * 31) // 255) | (((g * 31) // 255) << 5) | (((b * 31) // 255) << 10)


def verify_palette_constants() -> None:
    expected = [
        0,
        0,
        rgb15_from_rgb888(252, 156, 0),
        rgb15_from_rgb888(255, 211, 140),
        rgb15_from_rgb888(253, 191, 90),
    ]
    if PALETTE_RGB15[:5] != expected:
        raise SystemExit(f"palette RGB15 mismatch: {PALETTE_RGB15[:5]} != {expected}")


def pack_tile_row(indices: list[int]) -> int:
    value = 0
    for i, idx in enumerate(indices):
        value |= (idx & 15) << (i * 4)
    return value


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def convert(png_path: Path) -> tuple[list[int], list[list[int]], list[int], dict[str, object]]:
    verify_palette_constants()
    actual_hash = sha256_file(png_path)
    if actual_hash != SOURCE_HASH:
        raise SystemExit(
            f"{png_path}: source hash mismatch\n"
            f"  expected {SOURCE_HASH}\n"
            f"  actual   {actual_hash}"
        )

    rgba = Image.open(png_path).convert("RGBA")
    if rgba.size != (240, 160):
        raise SystemExit(f"{png_path}: expected 240x160, got {rgba.size}")

    index_grid: list[list[int]] = []
    for y in range(160):
        row: list[int] = []
        for x in range(240):
            r, g, b, a = rgba.getpixel((x, y))
            key = (0, 0, 0, 0) if a == 0 else (r, g, b, 255)
            if key not in SOURCE_TO_INDEX:
                raise SystemExit(f"{png_path}: unexpected color {key} at {x},{y}")
            if a not in (0, 255):
                raise SystemExit(f"{png_path}: non-binary alpha {a} at {x},{y}")
            row.append(SOURCE_TO_INDEX[key])
        index_grid.append(row)

    tile_to_id: dict[tuple[tuple[int, ...], ...], int] = {}
    tiles: list[list[int]] = []
    # Tile 0 reserved as fully transparent blank.
    blank = tuple(tuple(0 for _ in range(8)) for _ in range(8))
    tile_to_id[blank] = 0
    tiles.append([0] * 8)

    map_entries = [0] * (MAP_W * MAP_H)
    for ty in range(VISIBLE_TILE_H):
        for tx in range(VISIBLE_TILE_W):
            rows = []
            words: list[int] = []
            for ly in range(8):
                row = []
                for lx in range(8):
                    row.append(index_grid[ty * 8 + ly][tx * 8 + lx])
                rows.append(tuple(row))
                words.append(pack_tile_row(row))
            key = tuple(rows)
            if key not in tile_to_id:
                tile_to_id[key] = len(tiles)
                tiles.append(words)
            map_entries[ty * MAP_W + tx] = tile_to_id[key]

    if len(tiles) > 512:
        raise SystemExit(f"too many unique tiles: {len(tiles)}")

    palette = [0] * 16
    for i, value in enumerate(PALETTE_RGB15):
        if i < 16:
            palette[i] = value

    meta = {
        "source": str(png_path.relative_to(REPO_ROOT)).replace("\\", "/"),
        "source_hash": actual_hash,
        "unique_tiles": len(tiles),
        "map_w": MAP_W,
        "map_h": MAP_H,
        "visible_tile_w": VISIBLE_TILE_W,
        "visible_tile_h": VISIBLE_TILE_H,
        "palette_bank": 1,
        "palette_color_base": 16,
    }
    return palette, tiles, map_entries, meta


def emit_h(tile_count: int, meta: dict[str, object]) -> str:
    return f"""/* AUTOGENERATED, DO NOT EDIT
 * Source: {meta['source']}
 * Tool: tools/convert_dialogue_frame.py
 */
#ifndef DIALOGUE_FRAME_ASSET_H
#define DIALOGUE_FRAME_ASSET_H

#include "core/gba_types.h"

#define DIALOGUE_FRAME_TILE_COUNT {tile_count}
#define DIALOGUE_FRAME_TILE_WORDS (DIALOGUE_FRAME_TILE_COUNT * 8)
#define DIALOGUE_FRAME_MAP_W {meta['map_w']}
#define DIALOGUE_FRAME_MAP_H {meta['map_h']}
#define DIALOGUE_FRAME_MAP_ENTRIES (DIALOGUE_FRAME_MAP_W * DIALOGUE_FRAME_MAP_H)
#define DIALOGUE_FRAME_VISIBLE_TILE_W {meta['visible_tile_w']}
#define DIALOGUE_FRAME_VISIBLE_TILE_H {meta['visible_tile_h']}
#define DIALOGUE_FRAME_PALETTE_COUNT 16
#define DIALOGUE_FRAME_PALETTE_BANK 1

extern const u16 gDialogueFramePalette[DIALOGUE_FRAME_PALETTE_COUNT];
extern const u32 gDialogueFrameTiles[DIALOGUE_FRAME_TILE_WORDS];
extern const u16 gDialogueFrameMap[DIALOGUE_FRAME_MAP_ENTRIES];

#endif
"""


def emit_c(palette: list[int], tiles: list[list[int]], map_entries: list[int], meta: dict[str, object]) -> str:
    pal_lines = ",\n".join(f"    0x{v:04X}u" for v in palette[:16])
    tile_lines = []
    flat = [w for tile in tiles for w in tile]
    for i in range(0, len(flat), 4):
        chunk = ", ".join(f"0x{v:08X}u" for v in flat[i : i + 4])
        tile_lines.append(f"    {chunk},")
    map_lines = []
    for i in range(0, len(map_entries), 8):
        chunk = ", ".join(f"0x{v:04X}u" for v in map_entries[i : i + 8])
        map_lines.append(f"    {chunk},")
    return (
        "/* AUTOGENERATED, DO NOT EDIT\n"
        f" * Source: {meta['source']}\n"
        f" * SHA-256: {meta['source_hash']}\n"
        f" * Unique tiles: {meta['unique_tiles']}\n"
        " * Tool: tools/convert_dialogue_frame.py\n"
        " */\n"
        '#include "assets/dialogue_frame.h"\n'
        "\n"
        "const u16 gDialogueFramePalette[DIALOGUE_FRAME_PALETTE_COUNT] = {\n"
        f"{pal_lines}\n"
        "};\n"
        "\n"
        "const u32 gDialogueFrameTiles[DIALOGUE_FRAME_TILE_WORDS] = {\n"
        + "\n".join(tile_lines)
        + "\n};\n"
        "\n"
        "const u16 gDialogueFrameMap[DIALOGUE_FRAME_MAP_ENTRIES] = {\n"
        + "\n".join(map_lines)
        + "\n};\n"
    )


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name, dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=REPO_ROOT / "assets_src" / "ui" / "Dialogue Ui.png",
    )
    parser.add_argument(
        "--output-c",
        type=Path,
        default=REPO_ROOT / "src" / "assets" / "dialogue_frame.c",
    )
    parser.add_argument(
        "--output-h",
        type=Path,
        default=REPO_ROOT / "include" / "assets" / "dialogue_frame.h",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    palette, tiles, map_entries, meta = convert(args.input.resolve())
    header = emit_h(len(tiles), meta)
    source = emit_c(palette, tiles, map_entries, meta)

    if args.check:
        if not args.output_c.is_file() or not args.output_h.is_file():
            raise SystemExit("generated outputs missing")
        if args.output_c.read_text(encoding="utf-8") != source:
            raise SystemExit("dialogue_frame.c is stale")
        if args.output_h.read_text(encoding="utf-8") != header:
            raise SystemExit("dialogue_frame.h is stale")
        print("dialogue frame assets up to date")
        return 0

    write_atomic(args.output_h, header)
    write_atomic(args.output_c, source)
    print(
        f"Wrote {args.output_h.relative_to(REPO_ROOT)} and "
        f"{args.output_c.relative_to(REPO_ROOT)} "
        f"({len(tiles)} unique tiles)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
