#!/usr/bin/env python3
"""Convert eight directional overworld idle .aseprite files to GBA OBJ C arrays.

Facing order matches OverworldPlayerFacing:
  0 down, 1 down-left, 2 left, 3 up-left, 4 up, 5 up-right, 6 right, 7 down-right

Frame 0 = normal idle. Frame 1 (when present) = blink. Up/up-left/up-right are
single-frame and never invent a blink.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import os
import tempfile
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_W = 16
OUT_H = 32
TILE_WORDS = 64
FACING_COUNT = 8
FACING_FILES = (
    "idle_down.aseprite",
    "idle_downleft.aseprite",
    "idle_left.aseprite",
    "idle_upleft.aseprite",
    "idle_up.aseprite",
    "idle_upright.aseprite",
    "idle_right.aseprite",
    "idle_downright.aseprite",
)
# Upward facings never invent blinks even if a second frame appears.
NO_BLINK_FACINGS = {3, 4, 5}  # up-left, up, up-right


def load_ase_module():
    path = Path(__file__).with_name("inspect_aseprite_idle.py")
    spec = importlib.util.spec_from_file_location("inspect_aseprite_idle", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def rgb15(r8: int, g8: int, b8: int) -> int:
    return ((r8 * 31) // 255) | (((g8 * 31) // 255) << 5) | (((b8 * 31) // 255) << 10)


def pack_tile_row(indices: list[int]) -> int:
    value = 0
    for i, idx in enumerate(indices):
        value |= (idx & 15) << (i * 4)
    return value


def pad_rgba_to_16x32(frame: Image.Image) -> Image.Image:
    if frame.mode != "RGBA":
        frame = frame.convert("RGBA")
    src_w, src_h = frame.size
    if src_w > OUT_W or src_h > OUT_H:
        raise SystemExit(f"frame {frame.size} larger than {OUT_W}x{OUT_H}")
    canvas = Image.new("RGBA", (OUT_W, OUT_H), (0, 0, 0, 0))
    offset_x = (OUT_W - src_w) // 2
    offset_y = OUT_H - src_h
    canvas.paste(frame, (offset_x, offset_y), frame)
    return canvas


def build_palette_from_images(images: list[Image.Image]) -> list[tuple[int, int, int]]:
    """Index 0 = transparent; gather up to 15 unique opaque colors (first-seen order)."""
    colors: list[tuple[int, int, int]] = [(0, 0, 0)]
    seen = {(0, 0, 0)}
    for im in images:
        for r, g, b, a in im.getdata():
            if a < 128:
                continue
            rgb = (r, g, b)
            if rgb in seen:
                continue
            if len(colors) >= 16:
                break
            seen.add(rgb)
            colors.append(rgb)
        if len(colors) >= 16:
            break
    while len(colors) < 16:
        colors.append((0, 0, 0))
    return colors


def remap_rgba_to_palette(
    rgba: Image.Image, palette_rgb: list[tuple[int, int, int]]
) -> list[int]:
    indices: list[int] = []
    for r, g, b, a in rgba.getdata():
        if a < 128:
            indices.append(0)
            continue
        best = 1
        best_d = 1 << 30
        for i in range(1, 16):
            pr, pg, pb = palette_rgb[i]
            d = (r - pr) * (r - pr) + (g - pg) * (g - pg) + (b - pb) * (b - pb)
            if d < best_d:
                best_d = d
                best = i
        indices.append(best)
    return indices


def indices_to_tiles(indices: list[int]) -> list[int]:
    tiles: list[int] = []
    for tile_row in range(4):
        for tile_col in range(2):
            for y in range(8):
                py = tile_row * 8 + y
                row = []
                for x in range(8):
                    px = tile_col * 8 + x
                    row.append(indices[py * OUT_W + px])
                tiles.append(pack_tile_row(row))
    if len(tiles) != TILE_WORDS:
        raise SystemExit(f"expected {TILE_WORDS} tile words, got {len(tiles)}")
    return tiles


def emit_tile_array_2d(name: str, frames: list[list[int]]) -> str:
    lines = [f"const u32 {name}[{FACING_COUNT}][OVERWORLD_PLAYER_SPRITE_TILE_WORDS] = {{"]
    for facing, tiles in enumerate(frames):
        lines.append(f"    /* facing {facing} */")
        lines.append("    {")
        for i in range(0, len(tiles), 4):
            chunk = ", ".join(f"0x{v:08X}u" for v in tiles[i : i + 4])
            lines.append(f"        {chunk},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_c(
    palette: list[int],
    open_tiles: list[list[int]],
    blink_tiles: list[list[int]],
    has_blink: list[int],
    header_rel: str,
    source_note: str,
) -> str:
    pal_lines = ",\n".join(f"    0x{v:04X}u" for v in palette)
    blink_flags = ", ".join(str(v) for v in has_blink)
    return (
        "/* AUTOGENERATED, DO NOT EDIT\n"
        f" * Source: {source_note}\n"
        " * Tool: tools/convert_overworld_player_idles.py\n"
        " * Per facing: frame0 idle; frame1 blink when present (no invented up blinks).\n"
        " */\n"
        f'#include "{header_rel}"\n'
        "\n"
        "const u16 gOverworldPlayerSpritePalette"
        "[OVERWORLD_PLAYER_SPRITE_PALETTE_COUNT] = {\n"
        f"{pal_lines}\n"
        "};\n"
        "\n"
        f"const u8 gOverworldPlayerFacingHasBlink[OVERWORLD_PLAYER_FACING_SPRITE_COUNT] = {{"
        f" {blink_flags} }};\n"
        "\n"
        + emit_tile_array_2d("gOverworldPlayerIdleTiles", open_tiles)
        + "\n"
        + emit_tile_array_2d("gOverworldPlayerBlinkTiles", blink_tiles)
    )


def emit_h(source_note: str) -> str:
    return f"""/* AUTOGENERATED, DO NOT EDIT
 * Source: {source_note}
 * Tool: tools/convert_overworld_player_idles.py
 * Eight idle facings; blink tiles only where source has a second frame.
 */
#ifndef OVERWORLD_PLAYER_SPRITE_H
#define OVERWORLD_PLAYER_SPRITE_H

#include "core/gba_types.h"

#define OVERWORLD_PLAYER_SPRITE_WIDTH 16
#define OVERWORLD_PLAYER_SPRITE_HEIGHT 32
#define OVERWORLD_PLAYER_FACING_SPRITE_COUNT 8
#define OVERWORLD_PLAYER_SPRITE_TILE_COUNT 8
#define OVERWORLD_PLAYER_SPRITE_TILE_BYTES (OVERWORLD_PLAYER_SPRITE_TILE_COUNT * 32)
#define OVERWORLD_PLAYER_SPRITE_TILE_WORDS (OVERWORLD_PLAYER_SPRITE_TILE_BYTES / 4)
#define OVERWORLD_PLAYER_SPRITE_OBJ_TILE_INDEX 0
#define OVERWORLD_PLAYER_SPRITE_IDLE_OBJ_TILE_INDEX(facing) \\
    (OVERWORLD_PLAYER_SPRITE_OBJ_TILE_INDEX + ((facing) * OVERWORLD_PLAYER_SPRITE_TILE_COUNT))
#define OVERWORLD_PLAYER_SPRITE_BLINK_BANK_BASE \\
    (OVERWORLD_PLAYER_SPRITE_OBJ_TILE_INDEX + \\
     (OVERWORLD_PLAYER_FACING_SPRITE_COUNT * OVERWORLD_PLAYER_SPRITE_TILE_COUNT))
#define OVERWORLD_PLAYER_SPRITE_BLINK_OBJ_TILE_INDEX(facing) \\
    (OVERWORLD_PLAYER_SPRITE_BLINK_BANK_BASE + ((facing) * OVERWORLD_PLAYER_SPRITE_TILE_COUNT))
#define OVERWORLD_PLAYER_SPRITE_PALETTE_BANK 0
#define OVERWORLD_PLAYER_SPRITE_PALETTE_COUNT 16
/* Total OBJ tiles reserved: 8 facings * 8 idle + 8 facings * 8 blink = 128. */
#define OVERWORLD_PLAYER_SPRITE_TOTAL_TILE_COUNT \\
    (OVERWORLD_PLAYER_FACING_SPRITE_COUNT * OVERWORLD_PLAYER_SPRITE_TILE_COUNT * 2)

extern const u16 gOverworldPlayerSpritePalette[OVERWORLD_PLAYER_SPRITE_PALETTE_COUNT];
extern const u8 gOverworldPlayerFacingHasBlink[OVERWORLD_PLAYER_FACING_SPRITE_COUNT];
extern const u32 gOverworldPlayerIdleTiles
    [OVERWORLD_PLAYER_FACING_SPRITE_COUNT][OVERWORLD_PLAYER_SPRITE_TILE_WORDS];
extern const u32 gOverworldPlayerBlinkTiles
    [OVERWORLD_PLAYER_FACING_SPRITE_COUNT][OVERWORLD_PLAYER_SPRITE_TILE_WORDS];

_Static_assert(
    OVERWORLD_PLAYER_SPRITE_TILE_BYTES == 256,
    "Player OBJ pose must occupy 256 bytes");
_Static_assert(
    OVERWORLD_PLAYER_SPRITE_WIDTH == 16 && OVERWORLD_PLAYER_SPRITE_HEIGHT == 32,
    "Player OBJ must be 16x32");
_Static_assert(
    (OVERWORLD_PLAYER_SPRITE_OBJ_TILE_INDEX + OVERWORLD_PLAYER_SPRITE_TOTAL_TILE_COUNT)
        <= 1024,
    "Player idle+blink banks must fit in OBJ VRAM");
_Static_assert(
    (OVERWORLD_PLAYER_SPRITE_PALETTE_COUNT * 2) == 32,
    "Player OBJ palette must occupy 32 bytes");

#endif
"""


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def convert_aseprite_dir(ase_dir: Path, preview_dir: Path | None) -> tuple:
    ase = load_ase_module()
    rgba_frames: list[list[Image.Image]] = []
    has_blink: list[int] = []
    for facing, name in enumerate(FACING_FILES):
        path = ase_dir / name
        if not path.is_file():
            raise SystemExit(f"missing {path}")
        doc = ase.parse_ase(path)
        frames = []
        count = doc["frames"]
        use_blink = count >= 2 and facing not in NO_BLINK_FACINGS
        export_count = 2 if use_blink else 1
        if count >= 2 and facing in NO_BLINK_FACINGS:
            print(f"note: {name} has {count} frames but upward facing — blink ignored")
        for fi in range(export_count):
            img = ase.render_frame(doc, fi, mode="visible")
            if sum(1 for p in img.getdata() if p[3] > 0) <= 0:
                img = ase.render_frame(doc, fi, mode="all")
            padded = pad_rgba_to_16x32(img)
            frames.append(padded)
            if preview_dir is not None:
                preview_dir.mkdir(parents=True, exist_ok=True)
                padded.save(preview_dir / f"{Path(name).stem}_f{fi}_16x32.png")
        if not use_blink:
            # Duplicate open into blink slot so arrays stay rectangular; flag=0.
            frames.append(frames[0].copy())
            has_blink.append(0)
        else:
            has_blink.append(1)
        rgba_frames.append(frames)
        print(
            f"{name}: ase_frames={count} export_blink={use_blink} "
            f"size={doc['width']}x{doc['height']}"
        )

    flat_for_pal = [fr for facing in rgba_frames for fr in facing]
    palette_rgb = build_palette_from_images(flat_for_pal)
    palette = [0]
    for i in range(1, 16):
        r, g, b = palette_rgb[i]
        palette.append(rgb15(r, g, b))

    open_tiles: list[list[int]] = []
    blink_tiles: list[list[int]] = []
    for facing in range(FACING_COUNT):
        open_idx = remap_rgba_to_palette(rgba_frames[facing][0], palette_rgb)
        blink_idx = remap_rgba_to_palette(rgba_frames[facing][1], palette_rgb)
        if sum(1 for i in open_idx if i != 0) <= 0:
            raise SystemExit(f"facing {facing}: open frame has no opaque pixels")
        open_tiles.append(indices_to_tiles(open_idx))
        blink_tiles.append(indices_to_tiles(blink_idx))

    return palette, open_tiles, blink_tiles, has_blink


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--aseprite-dir",
        required=True,
        help="Directory containing idle_down.aseprite … idle_downright.aseprite",
    )
    parser.add_argument("--output-c", required=True)
    parser.add_argument("--output-h", required=True)
    parser.add_argument(
        "--preview-dir",
        default="",
        help="Optional directory for 16x32 preview PNGs",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    ase_dir = Path(args.aseprite_dir)
    preview = Path(args.preview_dir) if args.preview_dir else None
    palette, open_tiles, blink_tiles, has_blink = convert_aseprite_dir(ase_dir, preview)

    out_c = Path(args.output_c)
    out_h = Path(args.output_h)
    try:
        header_rel = out_h.resolve().relative_to(REPO_ROOT / "include").as_posix()
    except ValueError:
        header_rel = out_h.name
    source_note = ase_dir.as_posix() + " (8 idle_*.aseprite)"
    c_text = emit_c(palette, open_tiles, blink_tiles, has_blink, header_rel, source_note)
    h_text = emit_h(source_note)

    if args.check:
        if not out_c.is_file() or not out_h.is_file():
            raise SystemExit("generated player sprite outputs missing")
        if out_c.read_text(encoding="utf-8") != c_text or out_h.read_text(encoding="utf-8") != h_text:
            raise SystemExit("generated player sprite outputs are stale")
        return 0

    atomic_write(out_h, h_text)
    atomic_write(out_c, c_text)
    print("palette_bytes", len(palette) * 2)
    print("facings", FACING_COUNT)
    print("has_blink", has_blink)
    print("sha_dir", hashlib.sha256("".join(FACING_FILES).encode()).hexdigest()[:16])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
